package com.naviroq.patterns.behavioural.template.documentGenerator.types.html;

import com.naviroq.patterns.behavioural.template.documentGenerator.DocumentGenerator;

public class HtmlDocument extends DocumentGenerator {
    @Override
    protected void writeFooter() {
        System.out.println("  📝 Writing footer: <footer>Generated by HTML Generator</footer>");
    }

    @Override
    protected String getFileExtension() {
        return ".html";
    }

    @Override
    protected boolean isDebugMode() {
        return true; // Override to enable debug output
    }
}
